# Generated by Django 6.0.2 on 2026-02-26 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayRegeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('old_json', models.JSONField()),
                ('new_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_regenerations', to='itinerary.generateditinerary')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('budget_tier', models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], max_length=10)),
                ('vibe', models.CharField(choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('mixed', 'Mixed')], max_length=15)),
                ('group_type', models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('friends', 'Friends'), ('family', 'Family')], max_length=10)),
                ('meal_pref', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=10)),
                ('detail_level', models.CharField(choices=[('detailed', 'Detailed'), ('medium', 'Medium'), ('compact', 'Compact')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generateditinerary',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='itinerary.triprequest'),
        ),
    ]
