# Generated by Django 6.0.2 on 2026-02-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_data', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='generateditinerary',
            name='trip_request',
        ),
        migrations.AlterField(
            model_name='dayregeneration',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_regenerations', to='itinerary.itinerary'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('group_type', models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('friends', 'Friends'), ('family', 'Family')], max_length=10)),
                ('meal_pref', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=10)),
                ('vibe', models.CharField(choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('mixed', 'Mixed')], max_length=15)),
                ('budget_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('detail_level', models.CharField(choices=[('detailed', 'Detailed'), ('medium', 'Medium'), ('compact', 'Compact')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='itinerary.trip'),
        ),
        migrations.DeleteModel(
            name='TripRequest',
        ),
        migrations.DeleteModel(
            name='GeneratedItinerary',
        ),
    ]
