# Generated by Django 6.0.2 on 2026-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_itinerary_remove_generateditinerary_trip_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget_tier',
            field=models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], max_length=10),
        ),
    ]
