export const CITIES = [
  'Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat',
  'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara', 'Rajkot',
  'Varanasi', 'Amritsar', 'Tirupati', 'Shirdi', 'Mathura', 'Vrindavan', 'Dwarka', 'Puri', 'Bodh Gaya', 'Ajmer',
  'Rameswaram', 'Haridwar', 'Rishikesh', 'Ujjain', 'Nashik', 'Nathdwara', 'Somnath', 'Palitana', 'Madurai', 'Kanchipuram',
  'Agra', 'Jodhpur', 'Udaipur', 'Jaisalmer', 'Pushkar', 'Hampi', 'Khajuraho', 'Aurangabad', 'Mysore', 'Pondicherry',
  'Goa', 'Kochi', 'Varkala', 'Alibaug', 'Tarkarli', 'Diu', 'Daman', 'Mangalore', 'Udupi', 'Bekal',
  'Kanyakumari', 'Digha', 'Mandarmani', 'Vizag Beach', 'Karwar', 'Murudeshwar',
  'Shimla', 'Manali', 'Mussoorie', 'Nainital', 'Darjeeling', 'Ooty', 'Munnar', 'Coorg', 'Kodaikanal', 'Chikmagalur',
  'Kasauli', 'Lansdowne', 'Dalhousie', 'Dharamshala', 'McLeod Ganj', 'Spiti', 'Kufri', 'Mahabaleshwar', 'Lonavala', 'Matheran',
  'Mount Abu', 'Pachmarhi', 'Shillong', 'Cherrapunji', 'Tawang', 'Gangtok', 'Pelling', 'Lachung', 'Yuksom', 'Kasol',
  'Leh', 'Srinagar', 'Jammu', 'Kargil', 'Padum',
  'Uttarkashi', 'Kedarnath', 'Badrinath', 'Chopta', 'Auli', 'Munsiyari', 'Binsar', 'Chakrata', 'Dhanaulti',
  'Guwahati', 'Kaziranga', 'Tezpur', 'Dibrugarh', 'Imphal', 'Aizawl', 'Agartala', 'Kohima', 'Itanagar',
  'Port Blair', 'Havelock Island', 'Neil Island', 'Lakshadweep', 'Kavaratti',
  'Chandigarh', 'Dehradun', 'Siliguri', 'Ranchi', 'Raipur', 'Bhubaneswar', 'Tiruchirappalli', 'Vijayawada', 'Coimbatore', 'Salem',
]

export const LOADING_SENTENCES = [
  "✈️ Crafting your perfect trip across India...",
  "🗺️ Charting the most scenic route just for you...",
  "📅 Locking in your travel dates and schedule...",
  "🏨 Handpicking the finest stays along the way...",
  "🍽️ Discovering local flavours you'll absolutely love...",
  "🚆 Finding the best trains, cabs, and connections...",
  "🏔️ Exploring offbeat trails only locals know about...",
  "🛺 Arranging every transfer so you don't have to...",
  "🌅 Scouting the most breathtaking sunrise spots...",
  "🎭 Weaving culture, adventure, and relaxation together...",
  "🎒 Packing your days with unforgettable experiences...",
  "🌿 Finding that perfect chai stop between destinations...",
  "📍 Pinning every hidden gem onto your map...",
  "🗿 Uncovering centuries of history along your route...",
  "💫 Adding those little moments of pure magic...",
  "🛎️ Putting the finishing touches on your itinerary...",
  "🔍 Double-checking every detail one last time...",
  "🚀 Almost ready — your dream trip is nearly here!",
]
